export const FETCH_CART_REQUEST = 'FETCH_CART_REQUEST'
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS'
export const FETCH_CART_FAILURE = 'FETCH_CART_FAILURE'

export const FETCH_SEARCH_REQUEST = 'FETCH_SEARCH_REQUEST'
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS'
export const FETCH_SEARCH_FAILURE = 'FETCH_SEARCH_FAILURE'

export const FETCH_RANDOM_REQUEST = 'FETCH_RANDOM_REQUEST'
export const FETCH_RANDOM_SUCCESS = 'FETCH_RANDOM_SUCCESS'
export const FETCH_RANDOM_FAILURE = 'FETCH_RANDOM_FAILURE'